name: 'Automated Dependency Auditor'
description: 'Audit dependencies and generate a markdown report on outdated packages.'
author: 'Ali Sabry'
inputs: {}
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: search
  color: gray
tags:
  - nodejs
  - audit
  - dependencies
  - dependency-check
  - npm
  - devtools
  - ci
  - markdown
  - github-actions
  - security
