name: 'Automated Dependency Auditor + AI Wiki'
description: 'Audit dependencies and generate an AI-powered wiki using OpenAI.'
author: 'Ali Sabry'
inputs:
  openai_api_key:
    description: 'OpenAI API key'
    required: true

runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: search
  color: gray-dark

tags:
  - nodejs
  - audit
  - dependencies
  - dependency-check
  - openai
  - ai
  - devtools
  - markdown
  - documentation
  - github-actions

