const fs = require('fs');
const axios = require('axios');
const path = require('path');
const core = require('@actions/core');
const { spawn } = require('child_process');

// Utility to pad columns for better readability
function pad(str, length) {
  str = str || '';
  return str.length >= length ? str : str + ' '.repeat(length - str.length);
}

async function fetchLatestVersion(packageName) {
  try {
    const url = `https://registry.npmjs.org/${packageName.replace('/', '%2F')}/latest`;
    const response = await axios.get(url);
    return response.data.version;
  } catch (error) {
    console.warn(`[Warning] Failed to fetch ${packageName}: ${error.message}`);
    return null;
  }
}

function cleanVersion(version) {
  return version.replace(/[~^]/g, '');
}

function printProgress(current, total) {
  const percent = ((current / total) * 100).toFixed(1);
  console.log(`Progress: ${percent}% (${current}/${total})`);
}

async function generateReport() {
  const packagePath = path.join(process.cwd(), 'package.json');
  const rawData = fs.readFileSync(packagePath);
  const packageJson = JSON.parse(rawData);
  const dependencies = {
    ...packageJson.dependencies,
    ...packageJson.devDependencies
  };

  const report = [];
  const keys = Object.keys(dependencies);
  const total = keys.length;

  for (let i = 0; i < keys.length; i++) {
    const dep = keys[i];
    const current = dependencies[dep];
    const currentVersion = cleanVersion(current);
    const latestVersion = await fetchLatestVersion(dep);
    const status = (latestVersion === null || currentVersion === latestVersion) ? "Up-to-date ✅" : "Update available 🔴";
    report.push({ dep, current, latestVersion: latestVersion || 'N/A', status });
    printProgress(i + 1, total);
  }

  process.stdout.write("\n");

  const colWidths = {
    dep: 35,
    current: 18,
    latest: 18,
    status: 18
  };

  const header = [
    pad('Package', colWidths.dep),
    pad('Current Version', colWidths.current),
    pad('Latest Version', colWidths.latest),
    pad('Status', colWidths.status)
  ].join(' | ');

  const divider = [
    '-'.repeat(colWidths.dep),
    '-'.repeat(colWidths.current),
    '-'.repeat(colWidths.latest),
    '-'.repeat(colWidths.status)
  ].join(' | ');

  const lines = report.map(({ dep, current, latestVersion, status }) => {
    return [
      pad(dep, colWidths.dep),
      pad(current, colWidths.current),
      pad(latestVersion, colWidths.latest),
      pad(status, colWidths.status)
    ].join(' | ');
  });

  const markdown = [
    '# Dependency Audit Report',
    '',
    'This report was automatically generated by the Automated Dependency Auditor.',
    '',
    header,
    divider,
    ...lines
  ].join('\n');

  fs.writeFileSync('dependency_report.md', markdown);
  core.info("✔ Dependency report saved to dependency_report.md");
}

async function runDeepWiki() {
  const openaiKey = core.getInput('openai_api_key');
  const googleKey = core.getInput('google_api_key') || '';

  if (!openaiKey) {
    throw new Error('Missing required input: openai_api_key');
  }

  core.startGroup('🚀 Starting DeepWiki AI Wiki Generator');

  const configPath = path.join(__dirname, 'deepwiki', 'api', 'config.yaml');
  fs.writeFileSync(configPath, `OPENAI_API_KEY: ${openaiKey}\nGOOGLE_API_KEY: ${googleKey}\nVECTOR_STORE: local\n`);

  const pyProcess = spawn('python3', ['main.py'], {
    cwd: path.join(__dirname, 'deepwiki', 'api'),
    env: {
      ...process.env,
      OPENAI_API_KEY: openaiKey,
      GOOGLE_API_KEY: googleKey
    },
    stdio: 'inherit'
  });

  await new Promise((resolve, reject) => {
    pyProcess.on('close', (code) => {
      if (code === 0) {
        core.info('✅ DeepWiki generation completed successfully.');
        resolve();
      } else {
        reject(new Error(`DeepWiki process exited with code ${code}`));
      }
    });
  });

  core.endGroup();
}

// Entry point
(async () => {
  try {
    await generateReport();
    await runDeepWiki();
  } catch (err) {
    core.setFailed(`Action failed: ${err.message}`);
  }
})();

