const fs = require('fs');
const axios = require('axios');
const path = require('path');
const core = require('@actions/core');


// Utility to pad columns for better readability
function pad(str, length) {
  str = str || '';
  return str.length >= length ? str : str + ' '.repeat(length - str.length);
}

async function fetchLatestVersion(packageName) {
  try {
    const url = `https://registry.npmjs.org/${packageName.replace('/', '%2F')}/latest`;
    const response = await axios.get(url);
    return response.data.version;
  } catch (error) {
    console.warn(`[Warning] Failed to fetch ${packageName}: ${error.message}`);
    return null;
  }
}

function cleanVersion(version) {
  return version.replace(/[~^]/g, '');
}

function printProgress(current, total) {
  const percent = ((current / total) * 100).toFixed(1);
  process.stdout.clearLine(0);
  process.stdout.cursorTo(0);
  process.stdout.write(`Progress: ${percent}% (${current}/${total})`);
}

async function generateReport() {
  const packagePath = path.join(process.cwd(), 'package.json');
  const rawData = fs.readFileSync(packagePath);
  const packageJson = JSON.parse(rawData);
  const dependencies = {
    ...packageJson.dependencies,
    ...packageJson.devDependencies
  };

  const report = [];
  const keys = Object.keys(dependencies);
  const total = keys.length;

  for (let i = 0; i < keys.length; i++) {
    const dep = keys[i];
    const current = dependencies[dep];
    const currentVersion = cleanVersion(current);
    const latestVersion = await fetchLatestVersion(dep);
    const status = (latestVersion === null || currentVersion === latestVersion) ? "Up-to-date ✅" : "Update available 🔴";
    report.push({ dep, current, latestVersion: latestVersion || 'N/A', status });
    printProgress(i + 1, total);
  }

  process.stdout.write("\n");

  // Define column widths
  const colWidths = {
    dep: 35,
    current: 18,
    latest: 18,
    status: 18
  };

  const header = [
    pad('Package', colWidths.dep),
    pad('Current Version', colWidths.current),
    pad('Latest Version', colWidths.latest),
    pad('Status', colWidths.status)
  ].join(' | ');

  const divider = [
    '-'.repeat(colWidths.dep),
    '-'.repeat(colWidths.current),
    '-'.repeat(colWidths.latest),
    '-'.repeat(colWidths.status)
  ].join(' | ');

  const lines = report.map(({ dep, current, latestVersion, status }) => {
    return [
      pad(dep, colWidths.dep),
      pad(current, colWidths.current),
      pad(latestVersion, colWidths.latest),
      pad(status, colWidths.status)
    ].join(' | ');
  });

  const markdown = [
    '# Dependency Audit Report',
    '',
    'This report was automatically generated by the Automated Dependency Auditor.',
    '',
    header,
    divider,
    ...lines
  ].join('\n');

  fs.writeFileSync('dependency_report.md', markdown);
  core.info("✔ Dependency report saved to dependency_report.md");
}

generateReport();

