const fs = require('fs');
const axios = require('axios');
const path = require('path');
const core = require('@actions/core');
const { spawn } = require('child_process');


// Utility to pad columns for better readability
function pad(str, length) {
  str = str || '';
  return str.length >= length ? str : str + ' '.repeat(length - str.length);
}

async function fetchLatestVersion(packageName) {
  try {
    const url = `https://registry.npmjs.org/${packageName.replace('/', '%2F')}/latest`;
    const response = await axios.get(url);
    return response.data.version;
  } catch (error) {
    console.warn(`[Warning] Failed to fetch ${packageName}: ${error.message}`);
    return null;
  }
}

function cleanVersion(version) {
  return version.replace(/[~^]/g, '');
}

function printProgress(current, total) {
  const percent = ((current / total) * 100).toFixed(1);
  console.log(`Progress: ${percent}% (${current}/${total})`);
}

async function generateReport() {
  const packagePath = path.join(process.cwd(), 'package.json');
  const rawData = fs.readFileSync(packagePath);
  const packageJson = JSON.parse(rawData);
  const dependencies = {
    ...packageJson.dependencies,
    ...packageJson.devDependencies
  };

  const report = [];
  const keys = Object.keys(dependencies);
  const total = keys.length;

  for (let i = 0; i < keys.length; i++) {
    const dep = keys[i];
    const current = dependencies[dep];
    const currentVersion = cleanVersion(current);
    const latestVersion = await fetchLatestVersion(dep);
    const status = (latestVersion === null || currentVersion === latestVersion) ? "Up-to-date ✅" : "Update available 🔴";
    report.push({ dep, current, latestVersion: latestVersion || 'N/A', status });
    printProgress(i + 1, total);
  }

  process.stdout.write("\n");

  // Define column widths
  const colWidths = {
    dep: 35,
    current: 18,
    latest: 18,
    status: 18
  };

  const header = [
    pad('Package', colWidths.dep),
    pad('Current Version', colWidths.current),
    pad('Latest Version', colWidths.latest),
    pad('Status', colWidths.status)
  ].join(' | ');

  const divider = [
    '-'.repeat(colWidths.dep),
    '-'.repeat(colWidths.current),
    '-'.repeat(colWidths.latest),
    '-'.repeat(colWidths.status)
  ].join(' | ');

  const lines = report.map(({ dep, current, latestVersion, status }) => {
    return [
      pad(dep, colWidths.dep),
      pad(current, colWidths.current),
      pad(latestVersion, colWidths.latest),
      pad(status, colWidths.status)
    ].join(' | ');
  });

  const markdown = [
    '# Dependency Audit Report',
    '',
    'This report was automatically generated by the Automated Dependency Auditor.',
    '',
    header,
    divider,
    ...lines
  ].join('\n');

  fs.writeFileSync('dependency_report.md', markdown);
  core.info("✔ Dependency report saved to dependency_report.md");
}

async function waitForServer(timeout = 15000, interval = 1000) {
  return new Promise((resolve, reject) => {
    const start = Date.now();
    const check = async () => {
      try {
        await axios.get('http://localhost:8001/health');
        resolve();
      } catch {
        if (Date.now() - start > timeout) {
          reject(new Error('Timed out waiting for DeepWiki server'));
        } else {
          setTimeout(check, interval);
        }
      }
    };
    check();
  });
}

async function runDeepWiki() {
  const openaiKey = core.getInput('openai_api_key');
  if (!openaiKey) {
    throw new Error('Missing required input: openai_api_key');
  }

  core.startGroup('🚀 Starting DeepWiki AI Wiki Generator');

  const configPath = path.join(__dirname, 'deepwiki', 'api', 'config.yaml');
  fs.writeFileSync(configPath, `OPENAI_API_KEY: ${openaiKey}\nVECTOR_STORE: local\n`);

  const serverProcess = spawn('python3', ['-m', 'uvicorn', 'main:app', '--port', '8001'], {
    cwd: path.join(__dirname, 'deepwiki', 'api'),
    env: { ...process.env },
    stdio: 'inherit',
  });

  // Give server time to boot and confirm it works
  await waitForServer();

  core.info('✨ DeepWiki server is running. Generating AI documentation...');

  const response = await axios.post('http://localhost:8001/generate', {
    repo_path: process.cwd(),
    output_path: 'deepwiki_output',
  }, {
    headers: {
      Authorization: `Bearer ${openaiKey}`,
      'Content-Type': 'application/json',
    }
  });

  if (response.status === 200) {
    core.info('✅ DeepWiki generation complete.');
  } else {
    throw new Error(`DeepWiki API responded with status ${response.status}`);
  }

  core.endGroup();
}

// Entry point
(async () => {
  try {
    await generateReport();
    await runDeepWiki();
  } catch (err) {
    core.setFailed(`Action failed: ${err.message}`);
  }
})();
